image_research_task:
  description: >
    1. Search for images related to {topic} on the internet. 
    2. Generate descriptions and file names for all the images. 
    3. Download them and save them in a Redis database.
    4. Upload new images to Google Drive.
    5. Output the names and descriptions of new images found. 
  expected_output: >
    A JSON string with image urls and descriptive filenames, and whether the image is new and a count of the total number of new images.

