image_research_task:
  description: >
    1. Search for images related to {topic} on the internet. For each image, retrieve the 'source', 'link', 'title', 'imageUrl' fields from the search results. 
    2. Generate file names for all the images using the 'title' field. Make sure to include the file extention based on the filename of the searched image. 
    3. Download them and save them in a Redis cache.
    4. Upload new images to Google Cloud. 
    5. For all the images, use the DescriptionGenerator to generate a short description (100 words). Wait 30 seconds between requests to the DescriptionGenerator as it is slow and rate-limited.
    6. Upload the generated content for each uploaded image to Firestore. Ensure that you populate the Action Input with all the fields of the Content class correctly:
        file_name: the generated file name   
        generated_description: the generated paragraph describing the image
        original_url: the imageUrl field from the search results
        source_url: the link field from the search results
        sha256_hash: the image hash value obtained from the Redis tool
        source: the source field from the search results
        title: the title field from the search results
    If you encouter any errors or exceptions in the process, analyze them, reflect on your actions, and take remedial measures.
  expected_output: >
    The number of images whose content was uploaded to Firestore.
   

